# # https://docs.cypress.io/app/continuous-integration/github-actions
# name: Cypress Tests

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04

#     defaults:
#       run:
#         working-directory: ./frontend

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           working-directory: ./frontend
#           build: npm run build
#           start: npm start
#           browser: chrome
name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Frontend-relaterade kommandon
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build project
        working-directory: ./frontend
        run: npm run build

      - name: Start server
        working-directory: ./frontend
        run: PORT=4000 npm start &

      - name: Wait for frontend to be up
        run: npx wait-on http://localhost:4000

      # Backend-relaterade kommandon
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Start server
        working-directory: ./backend
        run: PORT=3000 npm run dev &

      - name: Wait for backend to be up
        run: npx wait-on http://localhost:3000

      # - name: Install dependencies
      #   run: npm install

      # - name: Build project
      #   run: npm run build

      # # Starta frontend på port 4000
      # - name: Start frontend server on port 4000
      #   run: |
      #     PORT=4000 npm start &  # Starta frontend i bakgrunden på port 4000


      # Vänta tills frontend är tillgänglig på port 4000
      # - name: Wait for frontend to be up
      #   run: |
      #     npx wait-on http://localhost:4000  # Vänta på att frontend-servern ska vara igång på port 4000

      # Starta backend-servern på port 3000
      # - name: Start backend server on port 3000
      #   run: |
      #     PORT=3000 npm run dev

      # # Vänta tills backend är tillgänglig på port 3000
      # - name: Wait for backend to be up
      #   run: |
      #     npx wait-on http://localhost:3000  # Vänta på att backend-servern ska vara igång på port 3000

      # Kör Cypress-tester
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          browser: chrome # Kör testerna i Chrome
